// logic/inlineStrongsBookLoaders.js
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/buildStrongsInlineAlignment.js
// DO NOT EDIT BY HAND — regenerate by running the build script.
//
// Static literal require() map for Metro/Expo bundler compatibility.
// Metro cannot bundle dynamically constructed require() paths, so every
// book file must have its own literal require() call in this map.
// ─────────────────────────────────────────────────────────────────────────────

"use strict";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const BOOK_LOADERS = Object.freeze({
  genesis: () => require("../assets/strong/alignment/genesis.json"),
  exodus: () => require("../assets/strong/alignment/exodus.json"),
  leviticus: () => require("../assets/strong/alignment/leviticus.json"),
  numbers: () => require("../assets/strong/alignment/numbers.json"),
  deuteronomy: () => require("../assets/strong/alignment/deuteronomy.json"),
  joshua: () => require("../assets/strong/alignment/joshua.json"),
  judges: () => require("../assets/strong/alignment/judges.json"),
  ruth: () => require("../assets/strong/alignment/ruth.json"),
  "1_samuel": () => require("../assets/strong/alignment/1_samuel.json"),
  "2_samuel": () => require("../assets/strong/alignment/2_samuel.json"),
  "1_kings": () => require("../assets/strong/alignment/1_kings.json"),
  "2_kings": () => require("../assets/strong/alignment/2_kings.json"),
  "1_chronicles": () => require("../assets/strong/alignment/1_chronicles.json"),
  "2_chronicles": () => require("../assets/strong/alignment/2_chronicles.json"),
  ezra: () => require("../assets/strong/alignment/ezra.json"),
  nehemiah: () => require("../assets/strong/alignment/nehemiah.json"),
  esther: () => require("../assets/strong/alignment/esther.json"),
  job: () => require("../assets/strong/alignment/job.json"),
  psalms: () => require("../assets/strong/alignment/psalms.json"),
  proverbs: () => require("../assets/strong/alignment/proverbs.json"),
  ecclesiastes: () => require("../assets/strong/alignment/ecclesiastes.json"),
  song_of_solomon: () => require("../assets/strong/alignment/song_of_solomon.json"),
  isaiah: () => require("../assets/strong/alignment/isaiah.json"),
  jeremiah: () => require("../assets/strong/alignment/jeremiah.json"),
  lamentations: () => require("../assets/strong/alignment/lamentations.json"),
  ezekiel: () => require("../assets/strong/alignment/ezekiel.json"),
  daniel: () => require("../assets/strong/alignment/daniel.json"),
  hosea: () => require("../assets/strong/alignment/hosea.json"),
  joel: () => require("../assets/strong/alignment/joel.json"),
  amos: () => require("../assets/strong/alignment/amos.json"),
  obadiah: () => require("../assets/strong/alignment/obadiah.json"),
  jonah: () => require("../assets/strong/alignment/jonah.json"),
  micah: () => require("../assets/strong/alignment/micah.json"),
  nahum: () => require("../assets/strong/alignment/nahum.json"),
  habakkuk: () => require("../assets/strong/alignment/habakkuk.json"),
  zephaniah: () => require("../assets/strong/alignment/zephaniah.json"),
  haggai: () => require("../assets/strong/alignment/haggai.json"),
  zechariah: () => require("../assets/strong/alignment/zechariah.json"),
  malachi: () => require("../assets/strong/alignment/malachi.json"),
  matthew: () => require("../assets/strong/alignment/matthew.json"),
  mark: () => require("../assets/strong/alignment/mark.json"),
  luke: () => require("../assets/strong/alignment/luke.json"),
  john: () => require("../assets/strong/alignment/john.json"),
  acts: () => require("../assets/strong/alignment/acts.json"),
  romans: () => require("../assets/strong/alignment/romans.json"),
  "1_corinthians": () => require("../assets/strong/alignment/1_corinthians.json"),
  "2_corinthians": () => require("../assets/strong/alignment/2_corinthians.json"),
  galatians: () => require("../assets/strong/alignment/galatians.json"),
  ephesians: () => require("../assets/strong/alignment/ephesians.json"),
  philippians: () => require("../assets/strong/alignment/philippians.json"),
  colossians: () => require("../assets/strong/alignment/colossians.json"),
  "1_thessalonians": () => require("../assets/strong/alignment/1_thessalonians.json"),
  "2_thessalonians": () => require("../assets/strong/alignment/2_thessalonians.json"),
  "1_timothy": () => require("../assets/strong/alignment/1_timothy.json"),
  "2_timothy": () => require("../assets/strong/alignment/2_timothy.json"),
  titus: () => require("../assets/strong/alignment/titus.json"),
  philemon: () => require("../assets/strong/alignment/philemon.json"),
  hebrews: () => require("../assets/strong/alignment/hebrews.json"),
  james: () => require("../assets/strong/alignment/james.json"),
  "1_peter": () => require("../assets/strong/alignment/1_peter.json"),
  "2_peter": () => require("../assets/strong/alignment/2_peter.json"),
  "1_john": () => require("../assets/strong/alignment/1_john.json"),
  "2_john": () => require("../assets/strong/alignment/2_john.json"),
  "3_john": () => require("../assets/strong/alignment/3_john.json"),
  jude: () => require("../assets/strong/alignment/jude.json"),
  revelation: () => require("../assets/strong/alignment/revelation.json"),
});

module.exports = { BOOK_LOADERS };
